### ISSUE TITLE
Peregrine TabsMedia_TitleSize

### ISSUE THREAD

**Issue by Kristie-S** [peregrine-cms/enhancements#77]
**Description**
The "Title" Feature on the Tabs-Media component does not allow for the heading options to be applied. This causes the title to remain the same size as the body text.

**Type**
Enhancement

**Steps to Replicate**

1. Load the "Tabs-Media" component into the container
2. Select the "Tabs-Media" component to bring up the editing pane
3. Turn on the "Show Title" toggle
4.  Enter a test title in the "Title" text box
Notice that there are no text editing features in the editing pane and the editing features on the top ribbon are disabled.

**Notes**
This feature enhancement can also be applied to the subtitle.  **This bug has been resolved on localhost:8080**

**Screenshot**
![image](https://user-images.githubusercontent.com/85252201/120843298-cc2d1a80-c522-11eb-8224-0fe43800daf1.png)

**Screencast Links**
https://drive.google.com/file/d/1F83xpQHrkbTU5I0nmBog416P9yDyKlKZ/view?usp=sharing

**Comment by ehdatheadwire** [comment]
Per @Kristie-S , this has been fixed on latest version of Peregrine-CMS. We should follow up with explanatory documentation so users know how to manage.
